use std::{
    fs::{self, File, OpenOptions},
    io::{self, BufReader, BufWriter, Write},
    path::{Path, PathBuf},
    process::Command,
};

use fs2::FileExt;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use subtle::ConstantTimeEq;
use thiserror::Error;
use uuid::Uuid;

use crate::permissions::set_private_permissions;

/// Input needed to durably admit a Run before it generates work.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RunAdmission {
    /// Canonical Run UUID.
    pub id: String,
    /// Operator-approved absolute generated-work ceiling.
    pub generated_work_ceiling: u64,
    /// Relative Park expiry applied when this Run later Parks.
    pub park_ttl_ms: u64,
}

/// Initialized ACP Session identity attached after Agent startup.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RunSession {
    /// Admitted Run UUID.
    pub id: String,
    /// Agent-scoped Session actor that owns the Run.
    pub session_id: String,
    /// Configured Agent name used for reconstruction.
    pub agent: String,
    /// Agent-side ACP Session identifier.
    pub acp_session_id: String,
    /// Working directory used for reconstruction.
    pub working_dir: String,
    /// Whether admission confirmed ACP `session/load` support.
    pub load_session: bool,
}

/// Durable generated-work accounting owned by one Run.
#[derive(Clone, Debug, Deserialize, PartialEq, Eq, Serialize)]
pub struct GeneratedWorkBudget {
    /// Monotonic absolute ceiling approved for this Run.
    pub ceiling: u64,
    /// Outputs already generated by this Run.
    pub consumed: u64,
    /// Capacity held by pending Generator operations.
    pub reserved: u64,
    pending: Vec<PendingGeneration>,
    outputs: Vec<GeneratedOutput>,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Eq, Serialize)]
struct PendingGeneration {
    mutation_id: String,
    kind: String,
    units: u64,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Eq, Serialize)]
struct GeneratedOutput {
    mutation_id: String,
    kind: String,
    external_id: String,
}

/// One caller request to reserve generated-work capacity.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct GeneratedWorkReservation {
    /// Admitted Run authorizing this reservation.
    pub run_id: String,
    /// Secret generation capability issued at admission.
    pub token: String,
    /// Stable UUID reused for retries of the same mutation.
    pub mutation_id: String,
    /// Kind of output being generated, currently `beads_issue`.
    pub kind: String,
    /// Positive amount of capacity to reserve.
    pub units: u64,
}

/// Idempotent result of attempting a generated-work reservation.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ReserveResult {
    /// Capacity was newly reserved; execution may begin.
    Reserved,
    /// This mutation already has a reservation awaiting reconciliation.
    Pending,
    /// This mutation's output was already confirmed.
    Consumed,
    /// Capacity is exhausted and the Run is Parked.
    Exhausted,
}

/// Idempotent result of an operator resume request.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ResumeResult {
    /// The Run is active and may continue.
    Active,
    /// A cold Session is being reconstructed under a bounded lease.
    Resuming,
    /// Reconstruction failed; the Run remains cold-Parked.
    ColdParked,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Eq, Serialize)]
struct ResumeAttempt {
    operation_id: String,
    deadline_ms: u64,
    result: String,
}

/// Input needed to persist a cold-Parked Run.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RunDraft {
    /// Canonical Run UUID.
    pub id: String,
    /// Agent-scoped Session identity that claimed the work.
    pub session_id: String,
    /// Configured Agent name used to reload the ACP Session.
    pub agent: String,
    /// Agent-side ACP Session identifier.
    pub acp_session_id: String,
    /// Working directory used when reloading the ACP Session.
    pub working_dir: String,
    /// Whether admission confirmed ACP `session/load` support.
    pub load_session: bool,
    /// Beads claims to release if this Park expires.
    pub claimed_issue_ids: Vec<String>,
}

/// Durable Run state retained after cleanup for Forensics correlation.
#[derive(Clone, Debug, Deserialize, PartialEq, Eq, Serialize)]
pub struct Run {
    /// Storage schema version.
    pub schema_version: u8,
    /// Monotonic durable revision used by invalidation clients.
    pub revision: u64,
    /// Run UUID.
    pub id: String,
    /// Session identity used to form a truthful reaper actor.
    pub session_id: Option<String>,
    /// Configured Agent name used to reload the ACP Session.
    pub agent: Option<String>,
    /// Agent-side ACP Session identifier.
    pub acp_session_id: Option<String>,
    /// Working directory used when reloading the ACP Session.
    pub working_dir: Option<String>,
    /// Whether admission confirmed ACP `session/load` support.
    pub load_session: Option<bool>,
    /// One of `admitted`, `active`, `parked`, `cold_parked`, `resuming`, or `disposed`.
    pub state: String,
    /// Relative Park expiry declared at admission.
    pub park_ttl_ms: u64,
    /// Time when the current Park began.
    pub parked_at_ms: Option<u64>,
    /// Cold-Park expiry.
    pub park_expires_at_ms: u64,
    /// Mutation refused when generated-work exhaustion triggered this Park.
    pub triggering_mutation_id: Option<String>,
    resume_attempt: Option<ResumeAttempt>,
    /// Run-wide generated-work accounting.
    pub generated_work: GeneratedWorkBudget,
    generate_token_sha256: String,
    cleanup: Vec<CleanupEntry>,
}

/// Non-sensitive authoritative Run projection for local observers.
#[derive(Clone, Debug, Deserialize, PartialEq, Eq, Serialize)]
pub struct RunView {
    /// Run UUID.
    pub id: String,
    /// Monotonic durable revision for optimistic concurrency.
    pub revision: u64,
    /// Durable lifecycle state, as in [`Run::state`].
    pub state: String,
    /// Agent-scoped actor, when a Session is attached.
    pub session_id: Option<String>,
    /// Operator-approved absolute capacity ceiling.
    pub generated_work_ceiling: u64,
    /// Capacity consumed by confirmed outputs.
    pub generated_work_consumed: u64,
    /// Capacity held for pending mutations.
    pub generated_work_reserved: u64,
    /// Mutations awaiting reconciliation.
    pub pending_mutation_ids: Vec<String>,
    /// Refused mutation that caused the Run to Park.
    pub triggering_mutation_id: Option<String>,
    /// Park expiry as Unix epoch milliseconds; zero when no expiry is set.
    pub park_expires_at_ms: u64,
    /// Most recent resume attempt's stable identifier, if any.
    pub resume_operation_id: Option<String>,
    /// Resume lease deadline as Unix epoch milliseconds, if any.
    pub resume_deadline_ms: Option<u64>,
}

impl Run {
    /// Resolve a confirmed generated issue by mutation identity.
    #[must_use]
    pub fn generated_issue(&self, mutation_id: &str) -> Option<&str> {
        self.generated_work
            .outputs
            .iter()
            .find(|output| output.mutation_id == mutation_id)
            .map(|output| output.external_id.as_str())
    }
}

/// Public summary of a resumable durable Run.
#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
pub struct RunSummary {
    /// Run UUID.
    pub id: String,
    /// Configured Agent name.
    pub agent: String,
    /// Agent-side ACP Session identifier.
    pub acp_session_id: String,
    /// Working directory used for resume.
    pub working_dir: String,
    /// Current durable state.
    pub state: String,
    /// Time when the current Park began.
    pub parked_at_ms: u64,
    /// Cold-Park expiry.
    pub park_expires_at_ms: u64,
    /// Run-wide generated-work accounting.
    pub generated_work: GeneratedWorkBudget,
    /// Beads claims held by this Run.
    pub claims: Vec<String>,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Eq, Serialize)]
struct CleanupEntry {
    issue_id: String,
    completed: bool,
}

/// One pre-authorized claim-release action for the Beads adapter.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ReapAction {
    /// Previously recorded issue whose claim may be released.
    pub issue_id: String,
    /// Attributable reaper actor derived from the Run's Session identity.
    pub actor: String,
}

/// Outcome of one `reap_expired` pass, so a caller can log what happened instead of discarding it.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct ReapSummary {
    /// Runs whose claims all released and were transitioned to `disposed`.
    pub disposed: usize,
    /// Runs where at least one claim release failed this pass: `(run id, error message)`.
    /// Left `cold_parked`/`resuming` with the failing claim(s) still incomplete for a later retry.
    pub failed: Vec<(String, String)>,
}

/// Narrow adapter that can only release a pre-recorded Beads claim.
#[derive(Clone, Debug)]
pub struct BeadsCleanup {
    workspace: PathBuf,
    executable: PathBuf,
}

impl BeadsCleanup {
    /// Bind cleanup to one explicit Beads workspace and an explicit `br` executable.
    ///
    /// The executable must be a resolvable path or absolute path, not a bare name relying on
    /// the caller's `PATH`: a long-running daemon's `PATH` is not guaranteed to contain `br`
    /// (e.g. a systemd unit's minimal default), and a bare-name lookup fails silently when the
    /// caller discards this method's `Result` (louiselm-hvot).
    ///
    /// # Errors
    /// Rejects a workspace without a `.beads` directory.
    pub fn new(
        workspace: impl AsRef<Path>,
        executable: impl Into<PathBuf>,
    ) -> Result<Self, RunStoreError> {
        let workspace = workspace.as_ref();
        if !workspace.join(".beads").is_dir() {
            return Err(RunStoreError::Invalid(
                "Beads workspace has no .beads directory".to_owned(),
            ));
        }
        Ok(Self {
            workspace: workspace.to_path_buf(),
            executable: executable.into(),
        })
    }

    /// Release exactly the supplied claim; it cannot create or select work.
    ///
    /// # Errors
    /// Returns the process-start error or Beads stderr on a nonzero exit.
    pub fn release(&self, action: &ReapAction) -> Result<(), String> {
        let output = Command::new(&self.executable)
            .args(self.arguments(action))
            .current_dir(&self.workspace)
            .output()
            .map_err(|error| error.to_string())?;
        if output.status.success() {
            Ok(())
        } else {
            Err(String::from_utf8_lossy(&output.stderr).trim().to_owned())
        }
    }

    /// Exact constrained command shape used for one release.
    #[must_use]
    pub fn arguments<'a>(&self, action: &'a ReapAction) -> [&'a str; 7] {
        [
            "update",
            &action.issue_id,
            "--assignee",
            "",
            "--actor",
            &action.actor,
            "--json",
        ]
    }
}

/// Durable Run-store failure.
#[derive(Debug, Error)]
pub enum RunStoreError {
    /// Run data violates the local storage contract.
    #[error("invalid run: {0}")]
    Invalid(String),
    /// Run storage failed.
    #[error("run storage failed: {0}")]
    Io(#[from] io::Error),
    /// Persisted Run data is malformed.
    #[error("run data is malformed: {0}")]
    Json(#[from] serde_json::Error),
}

/// Filesystem-backed Run records and their retry-safe cleanup journals.
#[derive(Clone, Debug)]
pub struct RunStore {
    root: PathBuf,
}

impl RunStore {
    /// Open or create the Run-record root.
    ///
    /// # Errors
    /// Returns filesystem or permission errors while securing the root directory.
    pub fn new(root: impl AsRef<Path>) -> Result<Self, RunStoreError> {
        fs::create_dir_all(root.as_ref())?;
        set_private_permissions(root.as_ref(), true)?;
        Ok(Self {
            root: root.as_ref().to_path_buf(),
        })
    }

    /// Persist one admitted Run before any stage may generate work.
    ///
    /// # Errors
    /// Rejects invalid admission data, capability tokens, or conflicting Run UUIDs;
    /// propagates lock, stored-record, and persistence errors.
    pub fn admit(&self, admission: RunAdmission, token: &str) -> Result<(), RunStoreError> {
        validate_admission(&admission)?;
        validate_token(token)?;
        self.locked(|| {
            let path = self.path(&admission.id);
            let run = Run {
                schema_version: 4,
                revision: 1,
                id: admission.id,
                session_id: None,
                agent: None,
                acp_session_id: None,
                working_dir: None,
                load_session: None,
                state: "admitted".to_owned(),
                park_ttl_ms: admission.park_ttl_ms,
                parked_at_ms: None,
                park_expires_at_ms: 0,
                triggering_mutation_id: None,
                resume_attempt: None,
                generated_work: GeneratedWorkBudget {
                    ceiling: admission.generated_work_ceiling,
                    consumed: 0,
                    reserved: 0,
                    pending: Vec::new(),
                    outputs: Vec::new(),
                },
                generate_token_sha256: token_sha256(token),
                cleanup: Vec::new(),
            };
            if path.exists() {
                return if self.run(&run.id)? == run {
                    Ok(())
                } else {
                    Err(RunStoreError::Invalid(
                        "Run UUID conflicts with existing record".to_owned(),
                    ))
                };
            }
            write_atomic(&path, &run)
        })
    }

    /// Attach the initialized ACP Session before the Run can generate work.
    ///
    /// # Errors
    /// Rejects invalid Session identities or a Run outside admission (except an
    /// identical active retry); propagates storage and revision-overflow errors.
    pub fn attach(&self, session: RunSession) -> Result<(), RunStoreError> {
        validate_session(&session)?;
        self.locked(|| {
            let mut run = self.run(&session.id)?;
            let same = run.session_id.as_deref() == Some(&session.session_id)
                && run.agent.as_deref() == Some(&session.agent)
                && run.acp_session_id.as_deref() == Some(&session.acp_session_id)
                && run.working_dir.as_deref() == Some(&session.working_dir)
                && run.load_session == Some(session.load_session);
            if run.state == "active" && same {
                return Ok(());
            }
            if run.state != "admitted" {
                return Err(RunStoreError::Invalid(
                    "only an admitted Run can attach a Session".to_owned(),
                ));
            }
            run.session_id = Some(session.session_id);
            run.agent = Some(session.agent);
            run.acp_session_id = Some(session.acp_session_id);
            run.working_dir = Some(session.working_dir);
            run.load_session = Some(session.load_session);
            "active".clone_into(&mut run.state);
            advance_revision(&mut run)?;
            write_atomic(&self.path(&run.id), &run)
        })
    }

    /// Reserve generated-work capacity before an external mutation begins.
    ///
    /// # Errors
    /// Rejects invalid reservations, capabilities, lifecycle state, or accounting
    /// overflow; propagates storage errors. Exhaustion is a [`ReserveResult`], not an error.
    pub fn reserve_generated_work(
        &self,
        reservation: GeneratedWorkReservation,
        now_ms: u64,
    ) -> Result<ReserveResult, RunStoreError> {
        validate_reservation(&reservation)?;
        self.locked(|| {
            let mut run = self.run(&reservation.run_id)?;
            verify_token(&run, &reservation.token)?;
            if run
                .generated_work
                .outputs
                .iter()
                .any(|output| output.mutation_id == reservation.mutation_id)
            {
                return Ok(ReserveResult::Consumed);
            }
            if run
                .generated_work
                .pending
                .iter()
                .any(|pending| pending.mutation_id == reservation.mutation_id)
            {
                return Ok(ReserveResult::Pending);
            }
            if run.state != "active" {
                return if run.state == "parked" {
                    Ok(ReserveResult::Exhausted)
                } else {
                    Err(RunStoreError::Invalid(
                        "generated work requires an active attached Run".to_owned(),
                    ))
                };
            }
            let occupied = run
                .generated_work
                .consumed
                .checked_add(run.generated_work.reserved)
                .and_then(|value| value.checked_add(reservation.units))
                .ok_or_else(|| {
                    RunStoreError::Invalid("generated-work accounting overflow".to_owned())
                })?;
            if occupied > run.generated_work.ceiling {
                "parked".clone_into(&mut run.state);
                run.parked_at_ms = Some(now_ms);
                run.park_expires_at_ms = now_ms.checked_add(run.park_ttl_ms).ok_or_else(|| {
                    RunStoreError::Invalid("Park expiry overflows epoch milliseconds".to_owned())
                })?;
                run.triggering_mutation_id = Some(reservation.mutation_id);
                advance_revision(&mut run)?;
                write_atomic(&self.path(&run.id), &run)?;
                return Ok(ReserveResult::Exhausted);
            }
            run.generated_work.reserved = run
                .generated_work
                .reserved
                .checked_add(reservation.units)
                .ok_or_else(|| {
                    RunStoreError::Invalid("generated-work reservation overflow".to_owned())
                })?;
            run.generated_work.pending.push(PendingGeneration {
                mutation_id: reservation.mutation_id,
                kind: reservation.kind,
                units: reservation.units,
            });
            advance_revision(&mut run)?;
            write_atomic(&self.path(&run.id), &run)?;
            Ok(ReserveResult::Reserved)
        })
    }

    /// Convert one unit of a pending reservation into a durable generated output.
    ///
    /// # Errors
    /// Rejects invalid identifiers, capabilities, absent reservations, or accounting
    /// overflow; propagates lock, stored-record, and persistence errors.
    pub fn confirm_generated_work(
        &self,
        run_id: &str,
        token: &str,
        mutation_id: &str,
        issue_id: &str,
    ) -> Result<(), RunStoreError> {
        validate_id(run_id)?;
        validate_id(mutation_id)?;
        if issue_id.is_empty() {
            return Err(RunStoreError::Invalid(
                "generated issue id is empty".to_owned(),
            ));
        }
        self.locked(|| {
            let mut run = self.run(run_id)?;
            verify_token(&run, token)?;
            if run.generated_issue(mutation_id) == Some(issue_id) {
                return Ok(());
            }
            let index = run
                .generated_work
                .pending
                .iter()
                .position(|pending| pending.mutation_id == mutation_id)
                .ok_or_else(|| {
                    RunStoreError::Invalid("generated-work reservation was not found".to_owned())
                })?;
            let (kind, remaining) = {
                let pending = &mut run.generated_work.pending[index];
                pending.units -= 1;
                (pending.kind.clone(), pending.units)
            };
            if remaining == 0 {
                run.generated_work.pending.remove(index);
            }
            run.generated_work.reserved -= 1;
            run.generated_work.consumed =
                run.generated_work.consumed.checked_add(1).ok_or_else(|| {
                    RunStoreError::Invalid("generated-work consumption overflow".to_owned())
                })?;
            run.generated_work.outputs.push(GeneratedOutput {
                mutation_id: mutation_id.to_owned(),
                kind,
                external_id: issue_id.to_owned(),
            });
            advance_revision(&mut run)?;
            write_atomic(&self.path(run_id), &run)
        })
    }

    /// Release one reservation after a mutation definitely did not start.
    ///
    /// # Errors
    /// Rejects invalid identifiers or capabilities; propagates storage and revision
    /// errors. A reservation that is already absent is an idempotent success.
    pub fn release_generated_work(
        &self,
        run_id: &str,
        token: &str,
        mutation_id: &str,
    ) -> Result<(), RunStoreError> {
        validate_id(run_id)?;
        validate_id(mutation_id)?;
        self.locked(|| {
            let mut run = self.run(run_id)?;
            verify_token(&run, token)?;
            let Some(index) = run
                .generated_work
                .pending
                .iter()
                .position(|pending| pending.mutation_id == mutation_id)
            else {
                return Ok(());
            };
            let pending = run.generated_work.pending.remove(index);
            run.generated_work.reserved -= pending.units;
            advance_revision(&mut run)?;
            write_atomic(&self.path(run_id), &run)
        })
    }

    /// Resolve the attached Session actor for a generate capability.
    ///
    /// # Errors
    /// Returns record-loading, capability-validation, or missing-Session errors.
    pub fn generation_actor(&self, run_id: &str, token: &str) -> Result<String, RunStoreError> {
        let run = self.run(run_id)?;
        verify_token(&run, token)?;
        run.session_id
            .ok_or_else(|| RunStoreError::Invalid("Run has no attached Session".to_owned()))
    }

    /// List pending mutation identities for crash reconciliation.
    ///
    /// # Errors
    /// Returns record-loading or capability-validation errors.
    pub fn pending_generation_ids(
        &self,
        run_id: &str,
        token: &str,
    ) -> Result<Vec<String>, RunStoreError> {
        let run = self.run(run_id)?;
        verify_token(&run, token)?;
        Ok(run
            .generated_work
            .pending
            .into_iter()
            .map(|pending| pending.mutation_id)
            .collect())
    }

    /// Persist one cold Park for an admitted Run. Repeating the same Park is safe.
    ///
    /// # Errors
    /// Rejects invalid or mismatched Session data, an incompatible lifecycle state,
    /// or timestamp/revision overflow; propagates storage errors.
    pub fn park_cold(&self, draft: RunDraft, now_ms: u64) -> Result<(), RunStoreError> {
        validate_draft(&draft)?;
        self.locked(|| {
            let mut run = self.run(&draft.id)?;
            if run.session_id.as_deref() != Some(&draft.session_id)
                || run.agent.as_deref() != Some(&draft.agent)
                || run.acp_session_id.as_deref() != Some(&draft.acp_session_id)
                || run.working_dir.as_deref() != Some(&draft.working_dir)
                || run.load_session != Some(draft.load_session)
            {
                return Err(RunStoreError::Invalid(
                    "cold Park identity differs from admitted Run".to_owned(),
                ));
            }
            let cleanup = draft
                .claimed_issue_ids
                .into_iter()
                .map(|issue_id| CleanupEntry {
                    issue_id,
                    completed: false,
                })
                .collect::<Vec<_>>();
            if run.state == "cold_parked" && run.cleanup == cleanup {
                return Ok(());
            }
            if run.state != "active" && run.state != "parked" {
                return Err(RunStoreError::Invalid(
                    "only an active or Parked admitted Run can be cold-Parked".to_owned(),
                ));
            }
            "cold_parked".clone_into(&mut run.state);
            run.parked_at_ms = Some(now_ms);
            run.park_expires_at_ms = now_ms
                .checked_add(run.park_ttl_ms)
                .ok_or_else(|| RunStoreError::Invalid("Park expiry overflowed".to_owned()))?;
            run.cleanup = cleanup;
            advance_revision(&mut run)?;
            write_atomic(&self.path(&run.id), &run)
        })
    }

    /// Load one retained Run record.
    ///
    /// # Errors
    /// Rejects an invalid UUID, absent record, malformed JSON, or inconsistent
    /// stored schema/identity/accounting metadata; propagates file-read errors.
    pub fn run(&self, id: &str) -> Result<Run, RunStoreError> {
        validate_id(id)?;
        let path = self.path(id);
        if !path.is_file() {
            return Err(RunStoreError::Invalid("Run was not found".to_owned()));
        }
        let run: Run = serde_json::from_reader(BufReader::new(File::open(path)?))?;
        if run.schema_version != 4
            || run.revision == 0
            || run.id != id
            || run.generated_work.ceiling == 0
            || run.park_ttl_ms == 0
        {
            return Err(RunStoreError::Invalid("stored Run is invalid".to_owned()));
        }
        Ok(run)
    }

    /// Return every durable Run through a non-sensitive observer projection.
    ///
    /// # Errors
    /// Returns directory-read errors or [`Self::run`] errors for a retained record.
    pub fn snapshot(&self) -> Result<Vec<RunView>, RunStoreError> {
        let mut views = Vec::new();
        for entry in fs::read_dir(&self.root)? {
            let entry = entry?;
            let Some(id) = entry
                .file_name()
                .to_str()
                .and_then(|name| name.strip_suffix(".json"))
                .map(str::to_owned)
            else {
                continue;
            };
            if validate_id(&id).is_err() {
                continue;
            }
            let run = self.run(&id)?;
            views.push(RunView {
                id: run.id,
                revision: run.revision,
                state: run.state,
                session_id: run.session_id,
                generated_work_ceiling: run.generated_work.ceiling,
                generated_work_consumed: run.generated_work.consumed,
                generated_work_reserved: run.generated_work.reserved,
                pending_mutation_ids: run
                    .generated_work
                    .pending
                    .into_iter()
                    .map(|pending| pending.mutation_id)
                    .collect(),
                triggering_mutation_id: run.triggering_mutation_id,
                park_expires_at_ms: run.park_expires_at_ms,
                resume_operation_id: run
                    .resume_attempt
                    .as_ref()
                    .map(|attempt| attempt.operation_id.clone()),
                resume_deadline_ms: run
                    .resume_attempt
                    .as_ref()
                    .map(|attempt| attempt.deadline_ms),
            });
        }
        views.sort_by(|left, right| left.id.cmp(&right.id));
        Ok(views)
    }

    /// Load one non-sensitive authoritative Run projection.
    ///
    /// # Errors
    /// Returns [`Self::run`] errors when the record cannot be loaded or validated.
    pub fn view(&self, id: &str) -> Result<RunView, RunStoreError> {
        Ok(run_view(self.run(id)?))
    }

    /// Raise only the generated-work ceiling of a Parked Run using optimistic concurrency.
    ///
    /// # Errors
    /// Rejects a stale revision, non-Parked Run, non-increasing ceiling, or invalid
    /// identifier; propagates storage and revision-overflow errors.
    pub fn raise_generated_work_ceiling(
        &self,
        id: &str,
        expected_revision: u64,
        ceiling: u64,
    ) -> Result<RunView, RunStoreError> {
        validate_id(id)?;
        self.locked(|| {
            let mut run = self.run(id)?;
            require_revision(&run, expected_revision)?;
            if run.state != "parked" && run.state != "cold_parked" {
                return Err(RunStoreError::Invalid(
                    "only a Parked Run ceiling can be raised".to_owned(),
                ));
            }
            if ceiling <= run.generated_work.ceiling {
                return Err(RunStoreError::Invalid(
                    "generated-work ceiling must increase".to_owned(),
                ));
            }
            run.generated_work.ceiling = ceiling;
            advance_revision(&mut run)?;
            write_atomic(&self.path(id), &run)?;
            Ok(run_view(run))
        })
    }

    /// Begin an idempotent operator resume attempt.
    ///
    /// # Errors
    /// Rejects invalid identifiers/lease, stale revisions, incompatible lifecycle
    /// states, or deadline/revision overflow; propagates storage errors.
    pub fn begin_resume(
        &self,
        id: &str,
        expected_revision: u64,
        operation_id: &str,
        now_ms: u64,
        lease_ms: u64,
    ) -> Result<ResumeResult, RunStoreError> {
        validate_id(id)?;
        validate_id(operation_id)?;
        if lease_ms == 0 {
            return Err(RunStoreError::Invalid(
                "resume lease must be positive".to_owned(),
            ));
        }
        self.locked(|| {
            let mut run = self.run(id)?;
            if let Some(attempt) = &run.resume_attempt
                && attempt.operation_id == operation_id
            {
                return resume_result(&run);
            }
            require_revision(&run, expected_revision)?;
            if run.state != "parked" && run.state != "cold_parked" {
                return Err(RunStoreError::Invalid(
                    "only a Parked Run can resume".to_owned(),
                ));
            }
            let deadline_ms = now_ms
                .checked_add(lease_ms)
                .ok_or_else(|| RunStoreError::Invalid("resume deadline overflowed".to_owned()))?;
            let cold = run.state == "cold_parked";
            if cold { "resuming" } else { "active" }.clone_into(&mut run.state);
            run.resume_attempt = Some(ResumeAttempt {
                operation_id: operation_id.to_owned(),
                deadline_ms,
                result: if cold { "resuming" } else { "active" }.to_owned(),
            });
            advance_revision(&mut run)?;
            write_atomic(&self.path(id), &run)?;
            Ok(if cold {
                ResumeResult::Resuming
            } else {
                ResumeResult::Active
            })
        })
    }

    /// Finalize one cold reconstruction attempt without extending its lease.
    ///
    /// # Errors
    /// Rejects invalid identifiers, an absent or different attempt, stale revisions,
    /// or invalid persisted state; propagates storage and revision-overflow errors.
    pub fn finalize_resume(
        &self,
        id: &str,
        expected_revision: u64,
        operation_id: &str,
        succeeded: bool,
    ) -> Result<ResumeResult, RunStoreError> {
        validate_id(id)?;
        validate_id(operation_id)?;
        self.locked(|| {
            let mut run = self.run(id)?;
            let attempt = run
                .resume_attempt
                .as_ref()
                .ok_or_else(|| RunStoreError::Invalid("Run has no resume attempt".to_owned()))?;
            if attempt.operation_id != operation_id {
                return Err(RunStoreError::Invalid(
                    "resume operation differs".to_owned(),
                ));
            }
            if attempt.result != "resuming" {
                return resume_result(&run);
            }
            require_revision(&run, expected_revision)?;
            let deadline_ms = attempt.deadline_ms;
            if succeeded { "active" } else { "cold_parked" }.clone_into(&mut run.state);
            run.park_expires_at_ms = if succeeded { 0 } else { deadline_ms };
            run.resume_attempt = Some(ResumeAttempt {
                operation_id: operation_id.to_owned(),
                deadline_ms,
                result: if succeeded { "active" } else { "cold_parked" }.to_owned(),
            });
            advance_revision(&mut run)?;
            write_atomic(&self.path(id), &run)?;
            Ok(if succeeded {
                ResumeResult::Active
            } else {
                ResumeResult::ColdParked
            })
        })
    }

    /// List unexpired cold-Parked Runs without exposing cleanup journals.
    ///
    /// # Errors
    /// Returns directory/record-read errors or missing reconstruction metadata in
    /// a retained cold-Parked Run.
    pub fn list_resumable(&self, now_ms: u64) -> Result<Vec<RunSummary>, RunStoreError> {
        let mut summaries = Vec::new();
        for entry in fs::read_dir(&self.root)? {
            let entry = entry?;
            let file_name = entry.file_name();
            let Some(id) = file_name
                .to_str()
                .and_then(|name| name.strip_suffix(".json"))
            else {
                continue;
            };
            if validate_id(id).is_err() {
                continue;
            }
            let run = self.run(id)?;
            if run.state == "cold_parked" && run.park_expires_at_ms > now_ms {
                let agent = run
                    .agent
                    .ok_or_else(|| RunStoreError::Invalid("cold Park has no Agent".to_owned()))?;
                let acp_session_id = run.acp_session_id.ok_or_else(|| {
                    RunStoreError::Invalid("cold Park has no ACP Session".to_owned())
                })?;
                let working_dir = run.working_dir.ok_or_else(|| {
                    RunStoreError::Invalid("cold Park has no working directory".to_owned())
                })?;
                summaries.push(RunSummary {
                    id: run.id,
                    agent,
                    acp_session_id,
                    working_dir,
                    state: run.state,
                    parked_at_ms: run.parked_at_ms.ok_or_else(|| {
                        RunStoreError::Invalid("cold Park has no Park timestamp".to_owned())
                    })?,
                    park_expires_at_ms: run.park_expires_at_ms,
                    generated_work: run.generated_work,
                    claims: run
                        .cleanup
                        .iter()
                        .map(|entry| entry.issue_id.clone())
                        .collect(),
                });
            }
        }
        summaries.sort_by(|left, right| {
            right
                .parked_at_ms
                .cmp(&left.parked_at_ms)
                .then_with(|| left.id.cmp(&right.id))
        });
        Ok(summaries)
    }

    /// Reap due cold Parks through a narrow, caller-supplied cleanup adapter.
    ///
    /// A failed action is left incomplete and retried later, and does not stop this pass from
    /// reaping other, unrelated Runs: one permanently-failing release (a deleted issue, an
    /// unreachable `br`) must not block reaping for the rest of the store forever
    /// (louiselm-hvot). An adapter must make releasing a claim idempotent because a crash after
    /// its external effect and before this journal is written can replay that one action.
    ///
    /// # Errors
    /// Returns lock, directory, record, revision, or journal-write errors. Adapter
    /// failures are retained in [`ReapSummary::failed`] and remain retryable.
    pub fn reap_expired(
        &self,
        now_ms: u64,
        mut cleanup: impl FnMut(&ReapAction) -> Result<(), String>,
    ) -> Result<ReapSummary, RunStoreError> {
        self.locked(|| {
            let mut summary = ReapSummary::default();
            for entry in fs::read_dir(&self.root)? {
                let entry = entry?;
                let Some(id) = entry
                    .file_name()
                    .to_str()
                    .and_then(|name| name.strip_suffix(".json"))
                    .map(str::to_owned)
                else {
                    continue;
                };
                if validate_id(&id).is_err() {
                    continue;
                }
                let mut run = self.run(&id)?;
                let expires_at_ms = if run.state == "resuming" {
                    run.resume_attempt
                        .as_ref()
                        .map(|attempt| attempt.deadline_ms)
                } else if run.state == "cold_parked" {
                    Some(run.park_expires_at_ms)
                } else {
                    None
                };
                if expires_at_ms.is_none_or(|deadline| deadline > now_ms) {
                    continue;
                }
                let mut failure = None;
                for index in 0..run.cleanup.len() {
                    if run.cleanup[index].completed {
                        continue;
                    }
                    let action = ReapAction {
                        issue_id: run.cleanup[index].issue_id.clone(),
                        actor: format!(
                            "reaper/{}",
                            run.session_id.as_deref().ok_or_else(|| {
                                RunStoreError::Invalid("Parked Run has no Session".to_owned())
                            })?
                        ),
                    };
                    match cleanup(&action) {
                        Ok(()) => {
                            run.cleanup[index].completed = true;
                            advance_revision(&mut run)?;
                            write_atomic(&self.path(&id), &run)?;
                        }
                        Err(error) => {
                            failure = Some(error);
                            break;
                        }
                    }
                }
                if let Some(error) = failure {
                    summary.failed.push((id, error));
                    continue;
                }
                "disposed".clone_into(&mut run.state);
                advance_revision(&mut run)?;
                write_atomic(&self.path(&id), &run)?;
                summary.disposed += 1;
            }
            Ok(summary)
        })
    }

    fn path(&self, id: &str) -> PathBuf {
        self.root.join(format!("{id}.json"))
    }

    fn locked<T>(
        &self,
        operation: impl FnOnce() -> Result<T, RunStoreError>,
    ) -> Result<T, RunStoreError> {
        let lock_path = self.root.join(".lock");
        let lock = OpenOptions::new()
            .create(true)
            .truncate(false)
            .read(true)
            .write(true)
            .open(lock_path)?;
        set_private_permissions(&self.root.join(".lock"), false)?;
        lock.lock_exclusive()?;
        let result = operation();
        FileExt::unlock(&lock)?;
        result
    }
}

fn advance_revision(run: &mut Run) -> Result<(), RunStoreError> {
    run.revision = run
        .revision
        .checked_add(1)
        .ok_or_else(|| RunStoreError::Invalid("Run revision overflowed".to_owned()))?;
    Ok(())
}

fn require_revision(run: &Run, expected: u64) -> Result<(), RunStoreError> {
    if run.revision != expected {
        return Err(RunStoreError::Invalid(format!(
            "stale Run revision: expected {expected}, found {}",
            run.revision
        )));
    }
    Ok(())
}

fn resume_result(run: &Run) -> Result<ResumeResult, RunStoreError> {
    match run
        .resume_attempt
        .as_ref()
        .map(|attempt| attempt.result.as_str())
    {
        Some("active") => Ok(ResumeResult::Active),
        Some("resuming") => Ok(ResumeResult::Resuming),
        Some("cold_parked") => Ok(ResumeResult::ColdParked),
        _ => Err(RunStoreError::Invalid(
            "stored resume attempt is invalid".to_owned(),
        )),
    }
}

fn run_view(run: Run) -> RunView {
    RunView {
        id: run.id,
        revision: run.revision,
        state: run.state,
        session_id: run.session_id,
        generated_work_ceiling: run.generated_work.ceiling,
        generated_work_consumed: run.generated_work.consumed,
        generated_work_reserved: run.generated_work.reserved,
        pending_mutation_ids: run
            .generated_work
            .pending
            .into_iter()
            .map(|pending| pending.mutation_id)
            .collect(),
        triggering_mutation_id: run.triggering_mutation_id,
        park_expires_at_ms: run.park_expires_at_ms,
        resume_operation_id: run
            .resume_attempt
            .as_ref()
            .map(|attempt| attempt.operation_id.clone()),
        resume_deadline_ms: run
            .resume_attempt
            .as_ref()
            .map(|attempt| attempt.deadline_ms),
    }
}

fn validate_draft(draft: &RunDraft) -> Result<(), RunStoreError> {
    validate_id(&draft.id)?;
    if draft.session_id.is_empty()
        || draft.agent.is_empty()
        || draft.acp_session_id.is_empty()
        || draft.working_dir.is_empty()
        || !draft.load_session
        || draft
            .claimed_issue_ids
            .iter()
            .any(std::string::String::is_empty)
    {
        return Err(RunStoreError::Invalid(
            "Run fields must be non-empty and reloadable".to_owned(),
        ));
    }
    Ok(())
}

fn validate_admission(admission: &RunAdmission) -> Result<(), RunStoreError> {
    validate_id(&admission.id)?;
    if admission.generated_work_ceiling == 0 || admission.park_ttl_ms == 0 {
        return Err(RunStoreError::Invalid(
            "admitted Run ceiling and Park TTL must be positive".to_owned(),
        ));
    }
    Ok(())
}

fn validate_session(session: &RunSession) -> Result<(), RunStoreError> {
    validate_id(&session.id)?;
    if session.session_id.is_empty()
        || session.agent.is_empty()
        || session.acp_session_id.is_empty()
        || session.working_dir.is_empty()
    {
        return Err(RunStoreError::Invalid(
            "Run Session fields must be non-empty".to_owned(),
        ));
    }
    Ok(())
}

fn validate_reservation(reservation: &GeneratedWorkReservation) -> Result<(), RunStoreError> {
    validate_id(&reservation.run_id)?;
    validate_id(&reservation.mutation_id)?;
    validate_token(&reservation.token)?;
    if reservation.kind.is_empty() || reservation.units == 0 {
        return Err(RunStoreError::Invalid(
            "generated-work reservation requires a kind and positive units".to_owned(),
        ));
    }
    Ok(())
}

fn validate_token(token: &str) -> Result<(), RunStoreError> {
    if token.len() < 16 {
        return Err(RunStoreError::Invalid(
            "generate token is malformed".to_owned(),
        ));
    }
    Ok(())
}

fn token_sha256(token: &str) -> String {
    format!("{:x}", Sha256::digest(token.as_bytes()))
}

fn verify_token(run: &Run, token: &str) -> Result<(), RunStoreError> {
    validate_token(token)?;
    let expected = run.generate_token_sha256.as_bytes();
    let supplied = token_sha256(token);
    if expected.len() != supplied.len() || expected.ct_eq(supplied.as_bytes()).unwrap_u8() != 1 {
        return Err(RunStoreError::Invalid(
            "generate capability is invalid".to_owned(),
        ));
    }
    Ok(())
}

fn validate_id(id: &str) -> Result<(), RunStoreError> {
    let parsed = Uuid::parse_str(id)
        .map_err(|_| RunStoreError::Invalid("Run id must be a UUID".to_owned()))?;
    if parsed.to_string() != id.to_ascii_lowercase() {
        return Err(RunStoreError::Invalid(
            "Run id must use canonical UUID text".to_owned(),
        ));
    }
    Ok(())
}
fn write_atomic(path: &Path, value: &impl Serialize) -> Result<(), RunStoreError> {
    let temporary = path.with_file_name(format!(".run-{}", Uuid::new_v4()));
    let result = (|| {
        let file = OpenOptions::new()
            .create_new(true)
            .write(true)
            .open(&temporary)?;
        let mut writer = BufWriter::new(file);
        serde_json::to_writer_pretty(&mut writer, value)?;
        writer.write_all(b"\n")?;
        writer.flush()?;
        writer.get_ref().sync_all()?;
        fs::rename(&temporary, path)?;
        set_private_permissions(path, false)?;
        File::open(path.parent().ok_or_else(|| {
            io::Error::new(io::ErrorKind::InvalidInput, "Run path has no parent")
        })?)?
        .sync_all()?;
        Ok(())
    })();
    if temporary.exists() {
        let _ = fs::remove_file(temporary);
    }
    result
}
