local MiniTest = require("mini.test")
local Attention = require("louiselm.ui.attention")
local AttentionPaste = require("louiselm.ui.attention_paste")
local AttentionClient = require("louiselm.workflow.attention_client")
local RunClient = require("louiselm.workflow.run_client")
local Buffer = require("louiselm.ui.chat.buffer")

---@diagnostic disable-next-line: undefined-global -- Neovim injects its runtime API.
local nvim = vim
local T = MiniTest.new_set()

-- Advance the eligibility clock independently of scheduled socket acknowledgements.
local function fixture()
  local original_read, original_connect = RunClient.read_operator_capability, AttentionClient.connect
  local paste_dispatcher = AttentionPaste.new()
  local attention
  MiniTest.finally(function()
    if attention ~= nil then
      attention:dispose()
    end
    paste_dispatcher:dispose()
    RunClient.read_operator_capability, AttentionClient.connect = original_read, original_connect
  end)
  local clock, timers, eligible = 0, {}, {}
  local callbacks = 0
  local function acknowledge(callback, value)
    callbacks = callbacks + 1
    nvim.schedule(function()
      callback(value)
      callbacks = callbacks - 1
    end)
  end
  local client = { ready = false }
  function client:upsert(_, callback)
    acknowledge(callback, { generation = 1, items = {} })
    return true
  end
  function client:clear_session_kind(_, _, callback)
    acknowledge(callback, { generation = 1, items = {} })
    return true
  end
  function client:set_eligible(key, value, callback)
    eligible[#eligible + 1] = { session_id = key.subject_id, value = value, at_ms = clock }
    acknowledge(callback, { generation = 2, items = {} })
    return true
  end
  function client:dispose()
    return true
  end
  ---@diagnostic disable-next-line: duplicate-set-field -- Isolated asynchronous transport boundary.
  RunClient.read_operator_capability = function(_, callback)
    acknowledge(callback, "fixture-capability")
    return true
  end
  ---@diagnostic disable-next-line: duplicate-set-field -- Isolated asynchronous transport boundary.
  AttentionClient.connect = function(_, on_snapshot)
    acknowledge(function()
      client.ready = true
      on_snapshot({ generation = 0, items = {} })
    end)
    return client
  end
  attention = assert(Attention.new({
    paste_dispatcher = paste_dispatcher,
    schedule = function(delay, callback)
      timers[#timers + 1] = { due = clock + delay, run = callback }
    end,
    on_error = function(message)
      error(message)
    end,
  }))
  local function settle()
    local drained = false
    nvim.schedule(function()
      drained = true
    end)
    assert(nvim.wait(1000, function()
      return drained and callbacks == 0
    end))
  end
  return {
    attention = attention,
    eligible = eligible,
    settle = settle,
    ready = function(id)
      attention:turn_done({ status = "ready", agent = "codex", acp_session_id = id, current_turn = 1 }, false)
      settle()
    end,
    advance = function(ms)
      local target = clock + ms
      while timers[1] ~= nil and timers[1].due <= target do
        local timer = table.remove(timers, 1)
        clock = timer.due
        timer.run()
        settle()
      end
      clock = target
    end,
  }
end

T["streaming another Session does not postpone an unseen ready turn"] = function()
  local owner = Buffer.new({
    id = "streaming",
    name = "streaming",
    source = "new",
    agent = "codex",
    status = "prompting",
    working_dir = "/tmp",
    current_turn = 1,
    turn_options_changed = false,
    recording_pending = false,
    config_options = {},
    skills_policy = "off",
    embedded_context = false,
    commands = {},
    compactions = {},
  }, {
    markdown_highlighting = false,
    on_prompt_edit = function() end,
    prompt_prefix = function()
      return ""
    end,
    on_enter = function() end,
    submit = function() end,
  })
  MiniTest.finally(function()
    owner:dispose()
  end)
  owner:show(nvim.api.nvim_get_current_win(), false)
  local f = fixture()
  f.ready("unseen")
  for _ = 1, 3 do
    f.advance(9000)
    owner:render({ type = "chunk", session_id = "streaming", data = { text = "output\n" } })
    -- Deliver the events generated by programmatic buffer edits, without human input.
    nvim.api.nvim_exec_autocmds("TextChanged", { buffer = owner.buffer })
    nvim.api.nvim_exec_autocmds("CursorMoved", { buffer = owner.buffer })
  end
  f.advance(2999)
  MiniTest.expect.equality(f.eligible, {})
  f.advance(1)
  MiniTest.expect.equality(f.eligible, { { session_id = "unseen", value = true, at_ms = 30000 } })
end

T["real input elsewhere delays eligibility once without stale timer rearming"] = function()
  local f = fixture()
  f.ready("unseen")
  f.advance(10000)
  -- A typed key need not move the cursor or change text to count as user input.
  nvim.api.nvim_feedkeys(nvim.api.nvim_replace_termcodes("<Esc>", true, false, true), "ntx", false)
  f.settle()
  f.advance(29999)
  MiniTest.expect.equality(f.eligible, {})
  f.advance(1)
  MiniTest.expect.equality(f.eligible, { { session_id = "unseen", value = true, at_ms = 40000 } })
  f.advance(60000)
  MiniTest.expect.equality(#f.eligible, 1)
  nvim.api.nvim_exec_autocmds("FocusGained", {})
  f.advance(30000)
  MiniTest.expect.equality(#f.eligible, 1)
end

T["scripted paste delays eligibility by thirty seconds"] = function()
  local original_buffer = nvim.api.nvim_get_current_buf()
  local paste_buffer = nvim.api.nvim_create_buf(false, true)
  MiniTest.finally(function()
    if nvim.api.nvim_buf_is_valid(original_buffer) then
      nvim.api.nvim_set_current_buf(original_buffer)
    end
    if nvim.api.nvim_buf_is_valid(paste_buffer) then
      nvim.api.nvim_buf_delete(paste_buffer, { force = true })
    end
  end)
  nvim.api.nvim_set_current_buf(paste_buffer)

  local f = fixture()
  f.ready("unseen")
  f.advance(10000)
  nvim.api.nvim_paste("fixture", true, -1)
  f.settle()
  f.advance(29999)
  MiniTest.expect.equality(f.eligible, {})
  f.advance(1)
  MiniTest.expect.equality(f.eligible, { { session_id = "unseen", value = true, at_ms = 40000 } })
end

T["each streamed paste chunk restarts the inactivity delay"] = function()
  local original_buffer = nvim.api.nvim_get_current_buf()
  local paste_buffer = nvim.api.nvim_create_buf(false, true)
  MiniTest.finally(function()
    if nvim.api.nvim_buf_is_valid(original_buffer) then
      nvim.api.nvim_set_current_buf(original_buffer)
    end
    if nvim.api.nvim_buf_is_valid(paste_buffer) then
      nvim.api.nvim_buf_delete(paste_buffer, { force = true })
    end
  end)
  nvim.api.nvim_set_current_buf(paste_buffer)

  local f = fixture()
  f.ready("unseen")
  local function paste(phase)
    nvim.api.nvim_paste("fixture", true, phase)
    f.settle()
  end

  f.advance(10000)
  paste(1)
  f.advance(10000)
  paste(2)
  f.advance(10000)
  MiniTest.expect.equality(f.eligible, {})
  paste(3)
  f.advance(29999)
  MiniTest.expect.equality(f.eligible, {})
  f.advance(1)
  MiniTest.expect.equality(f.eligible, { { session_id = "unseen", value = true, at_ms = 60000 } })
end

T["focus activity delays permission conditions by exactly thirty seconds"] = function()
  local f = fixture()
  f.attention:permission_required({ acp_session_id = "waiting", current_turn = 1 }, { request_id = 1 })
  f.settle()
  f.advance(10000)
  nvim.api.nvim_exec_autocmds("FocusGained", {})
  f.advance(29999)
  MiniTest.expect.equality(f.eligible, {})
  f.advance(1)
  MiniTest.expect.equality(f.eligible, { { session_id = "waiting", value = true, at_ms = 40000 } })
end

T["superseded timers never rearm or repeat eligibility"] = function()
  local f = fixture()
  f.ready("unseen")
  f.advance(10000)
  nvim.api.nvim_exec_autocmds("FocusGained", {})
  f.advance(29999)
  MiniTest.expect.equality(f.eligible, {})
  f.advance(1)
  MiniTest.expect.equality(f.eligible, { { session_id = "unseen", value = true, at_ms = 40000 } })
  f.advance(60000)
  MiniTest.expect.equality(#f.eligible, 1)
end

T["seen resumed and disposed entries cannot notify through pending timers"] = function()
  local listeners = nvim.on_key()
  local f = fixture()
  f.ready("seen")
  f.ready("resumed")
  f.attention:seen("seen")
  f.attention:prompt_started("resumed")
  f.advance(30000)
  MiniTest.expect.equality(f.eligible, {})
  f.ready("disposed")
  nvim.api.nvim_feedkeys(nvim.api.nvim_replace_termcodes("<Esc>", true, false, true), "ntx", false)
  f.attention:dispose()
  f.settle()
  f.advance(60000)
  MiniTest.expect.equality(f.eligible, {})
  MiniTest.expect.equality(nvim.on_key(), listeners)
end

return T
