#!/usr/bin/env python3
"""Publish Release Please's plugin draft only after exact commit and bot-PR CI."""

import argparse
import base64
import json
import os
import re
import subprocess
import tomllib


def require(condition, message):
    if not condition:
        raise ValueError(message)


def publish(api, repository, run_id, component="plugin", prepare_assets=None):
    require(component in ("plugin", "capture"), "unsupported component")
    prefix = f"repos/{repository}/"

    def get(path):
        return api(prefix + path)

    def pages(path, field=None):
        page = 1
        while True:
            result = get(path + (f"&page={page}" if page > 1 else ""))
            items = result[field] if field else result
            yield from items
            if len(items) < 100:
                break
            page += 1

    workflow_id = get("actions/workflows/ci.yml")["id"]
    run = get(f"actions/runs/{run_id}")

    def successful(candidate, sha, event):
        return (candidate["workflow_id"] == workflow_id
                and candidate["head_sha"] == sha and candidate["event"] == event
                and candidate["status"] == "completed" and candidate["conclusion"] == "success"
                and candidate["repository"]["full_name"] == repository
                and candidate["head_repository"]["full_name"] == repository)

    sha = run["head_sha"]
    require(re.fullmatch(r"[0-9a-f]{40}", sha) and run["head_branch"] == "main"
            and successful(run, sha, "push"), "publication requires successful CI for an exact main push")

    def source(path):
        content = get(f"contents/{path}?ref={sha}")
        require(content["encoding"] == "base64", "unexpected source encoding")
        return base64.b64decode(content["content"]).decode()

    published = []
    for release in pages("releases?per_page=100"):
        tag = release["tag_name"]
        if not tag.startswith(component + "-v") or release["target_commitish"] != sha:
            continue
        require(re.fullmatch(component + r"-v0\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)", tag), "component release must remain 0.x.y")
        version = tag.removeprefix(component + "-v")
        require(version != "0.0.0", "0.0.0 is an unreleased checkout")
        require(get("immutable-releases")["enabled"], "enable GitHub immutable releases before publication")
        if component == "plugin":
            require(source("VERSION").strip() == version
                and json.loads(source(".release-please-manifest.json"))["."] == version
                and source("lua/louiselm/version.lua") == (
                    "-- Generated by scripts/generate-plugin-version; do not edit.\n"
                    f'return {{ version = "{version}" }} -- x-release-please-version\n'),
                    "tag, manifest, VERSION and consumed Lua version must agree")
            require(not release["assets"], "plugin release must have notes and only GitHub's complete source archives")
            changelog = "CHANGELOG.md"
        else:
            package = tomllib.loads(source("capture-service/Cargo.toml"))["package"]
            locked = [item for item in tomllib.loads(source("capture-service/Cargo.lock"))["package"] if item["name"] == "louiselm-capture"]
            require(package["name"] == "louiselm-capture" and package["version"] == version
                    and len(locked) == 1 and locked[0]["version"] == version
                    and json.loads(source(".release-please-manifest.json"))["capture-service"] == version,
                    "capture tag, Cargo metadata and manifest must agree")
            changelog = "capture-service/CHANGELOG.md"
            require(prepare_assets is not None, "capture publication requires checked assets")
        require(re.search(r"^## .*\b" + re.escape(version) + r"\b", source(changelog), re.M), "release changelog is missing")
        require(release["body"], "release notes are missing")

        refs = [ref for ref in get(f"git/matching-refs/tags/{tag}") if ref["ref"] == f"refs/tags/{tag}"]
        for ref in refs:
            obj = ref["object"]
            while obj["type"] == "tag":
                obj = get(f"git/tags/{obj['sha']}")["object"]
            require(obj["type"] == "commit" and obj["sha"] == sha, "existing release tag points to a different commit; never move it")
        if not release["draft"]:
            require(release["immutable"] and refs, "published release must already be immutable and tagged")
            if component == "capture":
                prepare_assets(repository, release, sha, version)
            published.append(dict(component=component, version=version, tag=tag, sha=sha, release_id=release["id"]))
            continue

        approved = []
        for linked in pages(f"commits/{sha}/pulls?per_page=100"):
            pr = get(f"pulls/{linked['number']}")
            if (pr["merged"] and pr["merge_commit_sha"] == sha
                    and pr["merged_by"]["type"] == "User"
                    and pr["base"]["ref"] == "main" and pr["base"]["repo"]["full_name"] == repository
                    and pr["head"]["repo"]["full_name"] == repository
                    and pr["head"]["ref"] == "release-please--branches--main--components--" + component
                    and any(label["name"] in ("autorelease: pending", "autorelease: tagged") for label in pr["labels"])):
                approved.append(pr)
        require(len(approved) == 1, "draft must come from one maintainer-merged component release PR")
        head = approved[0]["head"]["sha"]
        runs = pages(f"actions/workflows/ci.yml/runs?head_sha={head}&event=pull_request&per_page=100", "workflow_runs")
        require(any(successful(candidate, head, "pull_request") for candidate in runs), "actual release PR head has no successful pull_request CI run")

        if component == "capture":
            prepare_assets(repository, release, sha, version)
        # All preparation precedes publication. GitHub creates/locks the tag
        # and full source archives when publishing the immutable draft.
        result = api(prefix + f"releases/{release['id']}", {"draft": False, "make_latest": "false"})
        require(not result["draft"] and result["immutable"], "GitHub did not confirm immutable publication; inspect before retrying")
        published.append(dict(component=component, version=version, tag=tag, sha=sha, release_id=release["id"]))
    return published


def github_api(path, data=None):
    method = "PATCH" if data is not None else "GET"
    command = ["gh", "api", path, "--method", method]
    env = os.environ.copy()
    settings_token = env.pop("GH_IMMUTABILITY_TOKEN", None)
    settings_read = path == "repos/euri10/louiselm/immutable-releases" and data is None
    if settings_read:
        require(settings_token, "GH_IMMUTABILITY_TOKEN requires an App token with Administration read")
        env["GH_TOKEN"] = settings_token
    if data is not None:
        command += ["--input", "-"]
    try:
        result = subprocess.run(command, input=json.dumps(data) if data is not None else None,
                                text=True, capture_output=True, check=True, env=env)
    except subprocess.CalledProcessError as error:
        hint = "check the installed App has Administration read" if settings_read else "check token permissions and GitHub availability"
        # Do not print API response bodies or credential-bearing environments.
        raise RuntimeError(f"GitHub API {method} {path} failed (exit {error.returncode}); {hint}") from None
    return json.loads(result.stdout)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repository", required=True)
    parser.add_argument("--run-id", required=True, type=int)
    parser.add_argument("--component", choices=("plugin", "capture"), default="plugin")
    args = parser.parse_args()
    require(args.repository == "euri10/louiselm", "only the release authority may publish")
    if args.component == "capture":
        from capture_release import prepare_assets
    else:
        prepare_assets = None
    print(json.dumps(publish(github_api, args.repository, args.run_id, args.component, prepare_assets)))


if __name__ == "__main__":
    main()
