#!/usr/bin/env python3
"""Publication API fixtures: no credentials or network required."""

import base64
import copy
import importlib.util
import json
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import unittest

sys.dont_write_bytecode = True

def load(name):
    spec = importlib.util.spec_from_file_location(name, Path(__file__).with_name(name + ".py"))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


release = load("publish-plugin-release")
policy = load("check-release-commits")
SHA = "a" * 40
HEAD = "b" * 40
TAG = "plugin-v0.1.0"


class Publication(unittest.TestCase):
    def setUp(self):
        self.writes = []
        self.draft = dict(id=7, tag_name=TAG, target_commitish=SHA, draft=True,
                          immutable=False, assets=[], body="## 0.1.0\n\nFeatures", html_url="https://fixture/release")
        self.run = dict(id=10, workflow_id=3, head_sha=SHA, head_branch="main",
                        event="push", status="completed", conclusion="success",
                        repository={"full_name": "euri10/louiselm"}, head_repository={"full_name": "euri10/louiselm"})
        self.pr = dict(number=4, merged=True, merge_commit_sha=SHA, merged_by={"type": "User"},
                       base={"ref": "main", "repo": {"full_name": "euri10/louiselm"}},
                       head={"sha": HEAD, "ref": "release-please--branches--main--components--plugin",
                             "repo": {"full_name": "euri10/louiselm"}},
                       labels=[{"name": "autorelease: tagged"}])
        self.pr_run = dict(self.run, head_sha=HEAD, event="pull_request")
        self.immutable = True
        self.refs = []
        self.version = "0.1.0"

    def api(self, path, data=None):
        path = path.removeprefix("repos/euri10/louiselm/")
        if data is not None:
            self.writes.append((path, data))
            assert path == "releases/7" and data == {"draft": False, "make_latest": "false"}
            self.draft.update(draft=False, immutable=True)
            self.refs = [{"ref": "refs/tags/" + TAG, "object": {"type": "commit", "sha": SHA}}]
            return copy.deepcopy(self.draft)
        if path == "actions/runs/10": return self.run
        if path == "actions/workflows/ci.yml": return {"id": 3}
        if path == "immutable-releases": return {"enabled": self.immutable}
        if path == "releases?per_page=100": return [copy.deepcopy(self.draft)]
        if path == f"commits/{SHA}/pulls?per_page=100": return [{"number": 4}]
        if path == "pulls/4": return self.pr
        if path.startswith("actions/workflows/ci.yml/runs?"): return {"workflow_runs": [self.pr_run]}
        if path == "git/matching-refs/tags/" + TAG: return self.refs
        if path.startswith("contents/"):
            filename = path.removeprefix("contents/").split("?")[0]
            value = {
                "VERSION": self.version + "\n",
                ".release-please-manifest.json": json.dumps({".": "0.1.0"}),
                "lua/louiselm/version.lua": '-- Generated by scripts/generate-plugin-version; do not edit.\nreturn { version = "0.1.0" } -- x-release-please-version\n',
                "CHANGELOG.md": "# Plugin changelog\n\n## 0.1.0\n",
            }[filename]
            return {"encoding": "base64", "content": base64.b64encode(value.encode()).decode()}
        raise AssertionError(path)

    def publish(self):
        return release.publish(self.api, "euri10/louiselm", 10)

    def test_publish_then_retry_never_changes_published_bytes_or_tag(self):
        self.publish()
        self.assertEqual(len(self.writes), 1)
        original = copy.deepcopy(self.draft)
        self.publish()
        self.assertEqual(len(self.writes), 1)
        self.assertEqual(self.draft, original)

    def test_failures_remain_unpublished(self):
        for mutate in [
            lambda: self.run.update(conclusion="failure"),
            lambda: self.run.update(event="pull_request"),
            lambda: self.run.update(head_branch="other"),
            lambda: self.run.update(workflow_id=99),
            lambda: self.pr_run.update(head_sha="c" * 40),
            lambda: self.pr_run.update(conclusion="failure"),
            lambda: self.pr.update(merged_by={"type": "Bot"}),
            lambda: self.pr.update(merge_commit_sha="c" * 40),
            lambda: setattr(self, "immutable", False),
            lambda: setattr(self, "version", "0.2.0"),
            lambda: self.draft.update(assets=[{"name": "partial"}]),
            lambda: self.refs.append({"ref": "refs/tags/" + TAG, "object": {"type": "commit", "sha": "c" * 40}}),
        ]:
            with self.subTest(mutate=mutate):
                self.setUp()
                mutate()
                with self.assertRaises(ValueError): self.publish()
                self.assertEqual(self.writes, [])
                self.assertTrue(self.draft["draft"])

    def test_newer_unchecked_draft_is_not_published_by_older_ci(self):
        self.draft["target_commitish"] = "c" * 40
        self.publish()
        self.assertEqual(self.writes, [])

    def test_non_plugin_draft_is_ignored(self):
        self.draft["tag_name"] = "capture-v0.1.0"
        self.publish()
        self.assertEqual(self.writes, [])


class CommitPolicy(unittest.TestCase):
    def test_root_companion_and_site_files_cannot_drive_releases(self):
        for filename in policy.NON_PLUGIN_FILES:
            policy.validate("build: update tool", [filename], ["site"])
            for message in ["fix: tool", "feat!: tool", "chore: tool\n\nBREAKING CHANGE: upgrade", "chore: tool\n\nRelease-As: 1.0.0"]:
                with self.assertRaises(ValueError):
                    policy.validate(message, [filename, "site/index.md"], ["site"])
        policy.validate("feat: plugin and site", ["lua/x.lua", "package.json"], [])
        policy.validate("feat: site", ["site/index.md"], ["site"])

    def test_disposable_history_checks_actual_commit_messages_and_files(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)

            def git(*args):
                return subprocess.check_output([
                    "git", "-c", "user.name=fixture", "-c", "user.email=fixture@example.invalid",
                    "-c", "commit.gpgsign=false", "-c", "core.hooksPath=/dev/null", *args,
                ], cwd=root, text=True, stderr=subprocess.DEVNULL).strip()

            git("init", "--quiet")
            git("commit", "--quiet", "--allow-empty", "-m", "baseline")
            baseline = git("rev-parse", "HEAD")
            (root / "release-please-config.json").write_text(json.dumps({
                "bootstrap-sha": baseline, "packages": {".": {"exclude-paths": ["site"]}},
            }))
            (root / "package.json").write_text("{}")
            git("add", "package.json")
            git("commit", "--quiet", "-m", "build: site tooling")
            script = str(Path(policy.__file__).resolve())
            self.assertEqual(subprocess.run([sys.executable, script], cwd=root, capture_output=True).returncode, 0)
            (root / "package.json").write_text('{"private":true}')
            git("add", "package.json")
            git("commit", "--quiet", "-m", "feat: site tooling")
            result = subprocess.run([sys.executable, script], cwd=root, capture_output=True, text=True)
            self.assertNotEqual(result.returncode, 0)
            self.assertIn(git("rev-parse", "HEAD"), result.stderr)


class VersionProjection(unittest.TestCase):
    def test_stale_projection_and_unapproved_major_fail_the_real_check(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            (root / "scripts").mkdir()
            (root / "lua/louiselm").mkdir(parents=True)
            generator = root / "scripts/generate-plugin-version"
            shutil.copy(Path(__file__).with_name("generate-plugin-version"), generator)
            for version in ["0.7.2", "1.0.0"]:
                (root / "VERSION").write_text(version + "\n")
                (root / ".release-please-manifest.json").write_text(json.dumps({".": version}))
                result = subprocess.run([str(generator)], capture_output=True)
                self.assertEqual(result.returncode == 0, version == "0.7.2")
                if version == "0.7.2":
                    self.assertEqual(subprocess.run([str(generator), "--check"], capture_output=True).returncode, 0)
                    (root / "lua/louiselm/version.lua").write_text('return { version = "0.7.1" }\n')
                    self.assertNotEqual(subprocess.run([str(generator), "--check"], capture_output=True).returncode, 0)


if __name__ == "__main__":
    unittest.main()
