local M = {}

---Established public extension boundaries (AGENTS.md section 1). Each file
---is an explicit opt-in; a type is included only when one of its `defines`
---entries points at a listed file. Do not widen this list to a whole
---directory without checking every class it would newly expose.
M.SECTIONS = {
  {
    title = "Headless Session API",
    files = {
      "lua/louiselm/session/init.lua",
      "lua/louiselm/session/lifecycle.lua",
      "lua/louiselm/session/registry.lua",
      "lua/louiselm/session/limits.lua",
      "lua/louiselm/session/validation.lua",
    },
  },
  {
    title = "Typed Events",
    files = { "lua/louiselm/session/events.lua" },
  },
  {
    title = "Permission Policies",
    files = {
      "lua/louiselm/permission/init.lua",
      "lua/louiselm/permission/policy.lua",
      "lua/louiselm/permission/store.lua",
      "lua/louiselm/permission/human-prompt.lua",
    },
  },
  {
    title = "Agent Configuration",
    files = {
      "lua/louiselm/agent/init.lua",
      "lua/louiselm/agent/config.lua",
      "lua/louiselm/agent/health.lua",
      "lua/louiselm/agent/spawn.lua",
    },
  },
}

local HEADER = table.concat({
  "# LouiseLM Public API Appendix",
  "",
  "Generated by `scripts/generate-api-appendix` from LuaCATS annotations via",
  "`lua-language-server --doc`. Do not edit by hand.",
  "",
  "Scope: the established extension boundaries only -- the headless Session",
  "API, typed events, permission policies, and Agent configuration",
  "(AGENTS.md section 1). ACP transport internals, UI, schema machinery,",
  "mocks, and development helpers are intentionally excluded. AGENTS.md",
  "remains the sole Agent-facing (AX) contract; this appendix is a human",
  "API reference.",
}, "\n")

---@param entry table One doc.json top-level entry.
---@return string? file Source file of the entry's primary definition.
---@return integer line Definition start line, for deterministic ordering.
local function primary_definition(entry)
  local define = type(entry.defines) == "table" and entry.defines[1] or nil
  if type(define) ~= "table" or type(define.file) ~= "string" then
    return nil, 0
  end
  local line = type(define.start) == "table" and define.start[1] or 0
  return define.file, line
end

---@param field table One doc.json field entry.
---@return string
local function render_field(field)
  local line = string.format("- `%s: %s`", field.name, field.view)
  if type(field.desc) == "string" and field.desc ~= "" then
    line = line .. " -- " .. field.desc
  end
  return line
end

---@param entry table One doc.json top-level entry.
---@return string
local function render_body(entry)
  if type(entry.fields) == "table" and #entry.fields > 0 then
    local lines = {}
    for _, field in ipairs(entry.fields) do
      lines[#lines + 1] = render_field(field)
    end
    return table.concat(lines, "\n")
  end
  local define = type(entry.defines) == "table" and entry.defines[1] or nil
  if type(define) == "table" and type(define.desc) == "string" and define.desc ~= "" then
    return define.desc
  end
  local view = type(define) == "table" and define.view or entry.view or entry.name
  return string.format("```lua\n%s\n```", view)
end

---Render the curated public API appendix from a `lua-language-server --doc`
---export (decoded doc.json).
---@param entries table[] Decoded doc.json top-level entries.
---@param sections? table[] Override for M.SECTIONS; defaults to it.
---@return string markdown
function M.generate(entries, sections)
  sections = sections or M.SECTIONS

  local file_section = {}
  local file_order = {}
  for section_index, section in ipairs(sections) do
    for file_index, file in ipairs(section.files) do
      file_section[file] = section_index
      file_order[file] = file_index
    end
  end

  local buckets = {}
  for section_index in ipairs(sections) do
    buckets[section_index] = {}
  end

  for _, entry in ipairs(entries) do
    local file, line = primary_definition(entry)
    local section_index = file ~= nil and file_section[file] or nil
    if section_index ~= nil then
      local bucket = buckets[section_index]
      bucket[#bucket + 1] = { entry = entry, file = file, line = line }
    end
  end

  local parts = { HEADER }
  for section_index, section in ipairs(sections) do
    local bucket = buckets[section_index]
    table.sort(bucket, function(a, b)
      if a.file ~= b.file then
        return file_order[a.file] < file_order[b.file]
      end
      return a.line < b.line
    end)

    local section_lines = { "", "## " .. section.title }
    for _, item in ipairs(bucket) do
      section_lines[#section_lines + 1] = ""
      section_lines[#section_lines + 1] = "### " .. item.entry.name
      section_lines[#section_lines + 1] = ""
      section_lines[#section_lines + 1] = render_body(item.entry)
    end
    parts[#parts + 1] = table.concat(section_lines, "\n")
  end

  return table.concat(parts, "\n") .. "\n"
end

return M
