#!/bin/sh
set -eu

case "${1-}" in
  create|q)
    command=$1
    shift
    exec "${LOUISELM_CAPTURE:?}" --require-interface=1 run generate --command "$command" -- "$@"
    ;;
  *)
    exec "${LOUISELM_REAL_BR:?}" "$@"
    ;;
esac
